language: java
install: skip

os: linux
dist: xenial
jdk: openjdk14

env:
  global:
  - PGPORT=5432
git:
  depth: false
    
addons:
  sonarcloud:
    organization: "calvinhuynh-github"
    token: "$key"
  postgresql: "9.4"

script:
- ./gradlew assemble jacocoTestReport sonarqube