language: java
install: skip

os: linux
dist: xenial
jdk: openjdk14

git:
  depth: false
    
addons:
  sonarcloud:
    organization: "calvinhuynh-github"
    token: "$key"
  
script:
- ./gradlew build sonarqube